Hello: Hello World!
Aide: Need some help! 
Titre: Title
Datecreation: Date of making 
Catalogue: N° of catalogue
Auteur: Author
Hauteur: Height
Largeur: Width
Changerdelangue: Switch language
Changer: Switch
TitreSource: Create a source
TitreProprietaire: Create an owner
TitreEmplacement: Create a location
TitreExhibition: Create an exhibition
TitreOeuvre: Create a work
TitreAdd: Add
TitreFournisseur: Create a supplier
FieldName: Name
FieldReliability: Reliability
FieldKind: Type of collection
FieldCity: City
FieldCountry: Country
FieldStartDate: From
FieldEndDate: To
FieldDate: Date
FieldExhibitionName: Exhibition name
FieldTitre: Title
FieldUnknow: Unknow
NavbarHome: Home
NavbarCreate: Create
NavbarAddNewInformation: Add new information
NavbarLogin: Login
NavbarProfile: Profile
SitePrivate: Private
SiteMuseum: Museum
SiteWorkShop: Studio
SiteStore: Storage
SiteDomestic: Home
Description: Description
Link: Link
Format: Format
TitreCreate: Add a data about : 
Painting: Painting
Owner: Owner
LastOwner: Last owner
ShowOwner: Show owners
Exhibition: Exhibition
Location: Location
Localisation: Localization
LastLocalisation: Last localization
ShowLocalisation: Show localizations
Source: Source
Supplier: Supplier
TitreHOwner: Add a new owner for this painting
TitreHLocation: Add a new location for this painting
FieldConservationCond: Conservation condition
FieldNameExhibition: Name of exhibition
FieldAccurateStartDate: Accurate of begin date
FieldChronologyStartDate: Chronology of begin date
FieldAccurateEndDate: Accurate of end date
FieldChronologyEndDate: Chronology end date
PrecisionSource: Source accuracy
Precision: Accurate
NouveauTypeIntervention: A new type of intervention
NouveauTypeAlteration: A new type of alteration
Vernis: Varnish
Outil: Tool
Materiaux: Materials
StratigraphieComposition: Composition stratigraphy
Prenom: First name
Qualite: Profession
Adresse: Address
Composition: Composed by
SousCat: Sub-category of
NomCommercial : Trade name
Couleur: Color
Position : Positions (Layer0, Layer1, Layer2 etc.)
Type : Type
Nature : Nature
RechercherOeuvre: Search a painting
RechercherExposition: Search an exhibition
Rechercher: Search
AucunResultat: Not found
Dimension: Size
De: from
Aa: to
Annuler: Cancel
Modifier: Update
Supprimer: Delete
Historique: Historic
Support: Support
SupportExamen: Exam support
CouchePicturale: Pictorial layer
Examen: Examination
Intervention: Intervention
Analyse: Physical and chemical analyses
Conservation: Conservation
Travers: Travers
Contexture: Contexture
QuartRond: Presence of a round quard
ChassisCle: Presence of a key on the chassis
FournisseurChassis: Chassis supplier
FournisseurToile: Canvas supplier
Stratigraphie: Stratigraphy
Esthetique: Esthetique
Fragilite: Frailty
Alteration: Disturbance
Photo: Picture
Document: Document
Repentir: Repent
Laboratoire: Laboratory 
Observation: Observation
CoucheObservee: Observed layer
Technique: Technique
NouvellesDonnees: Proposition of new data 
Zone: area
Valider: submit
Fermer: close
TypeAlteration: Type of alteration 
TypeIntervention: Type of intervention 
Initiale: Init
PereExamen: This exam is a follow-up to a previous exam? 
Revers: Backhand access
AlterationPere: Alteration père
Email: Email address
Setting: Pages settings
VerificationKey: Verification key
Verifie: Verified
Active: Active
Role: Role
Produit: Product being used 
TypeDeStockage: Type of storage
NomExposition: Name of exhibition
Favoris: Favorite places
AutreLieu: Other places
NouveauEmplacementHP: Add this site new historical location for this work?
NouveauEmplacementFavorisHP: Add this location as the owner’s favorite storage location?
ModifierImage : Update the picture
AjouterImage: Add a picture 
Public: Autorisation de publication



