Hello: Bonjour le monde!
Aide: Page d'Aide
Titre: Titre
Datecreation: Date de création
Catalogue: N° du catalogue
Auteur: Auteur
Hauteur: Hauteur
Largeur: Largeur
Changerdelangue: Changer de langue
Changer: Changer
TitreSource: Créer une source
TitreProprietaire: Créer un propriétaire
TitreEmplacement: Créer un emplacement
TitreExhibition: Créer une exposition
TitreOeuvre: Créer une fiche / œuvre
TitreAdd: Ajouter
TitreFournisseur: Créer un fournisseur
FieldName: Nom
FieldReliability: Fiabilité
FieldKind: Type de collection
FieldCity: Ville
FieldCountry: Pays
FieldStartDate: Date de début
FieldEndDate: Date de fin
FieldDate: Date
FieldExhibitionName: Nom de l'exposition
FieldTitre: Titre
FieldUnknow: Inconnu
NavbarHome: Page principale
NavbarCreate: Créer
NavbarAddNewInformation: Ajouter une nouvelle information
NavbarLogin: Se connecter
NavbarProfile: Profil
SitePrivate: Prive(e)
SiteMuseum: Musée
SiteWorkShop: Atelier
SiteStore: Réserve
SiteDomestic: Usage privé
Description: Description
Link: Lien
Format: Format
TitreCreate: Vous souhaitez ajouter une information concernant : 
Painting: Œuvre
Owner: Propriétaire
LastOwner: Dernière appartenance
ShowOwner: Afficher les appartenances
Exhibition: Exposition
Location: Emplacement (lieu de stockage et exposition)
Localisation: Localisation
LastLocalisation: Dernière localisation
ShowLocalisation: Afficher les emplacements
Source: Source
Supplier: Fournisseur
TitreHOwner: Ajouter un nouveau propriétaire à cette œuvre
TitreHLocation: Ajouter un nouvel emplacement à cette œuvre
FieldConservationCond: État de conservation
FieldNameExhibition: Nom de l'exposition
FieldAccurateStartDate: Précision de la date de début
FieldChronologyStartDate: Chronologie de la date de début
FieldAccurateEndDate: Précision de la date de fin
FieldChronologyEndDate: Chronologie de la date de fin
PrecisionSource: Précision de la source
Precision: Précision
NouveauTypeIntervention: Un nouveau type d'intervention
NouveauTypeAlteration: Un nouveau type d'alteration
Vernis: Vernis
Outil: Outil
Materiaux: Matériaux
StratigraphieComposition: Stratigraphie de composition
Prenom: Prénom
Qualite: Qualité
Adresse: Adresse
Composition: Composition
SousCat: Sous catégorie de 
NomCommercial : Trade name
Couleur: Color
Position : Positions (Couche0, Couche1, Couche2 etc.)
Type : Type
Nature : Nature
RechercherOeuvre: Rechercher une œuvre
RechercherExposition: Rechercher une exposition
Rechercher: Rechercher
AucunResultat: Aucun Résultat
Dimension: Dimensions
De: de
Aa: à 
Annuler: Annuler
Modifier: modifier
Supprimer: Supprimer
Historique: Historique
Support: Support
SupportExamen: Support de l'examen
CouchePicturale: Couche picturale
Examen: Examen
Intervention: Intervention
Analyse: Analyse physico-chimique
Conservation: Conservation
Travers: Travers
Contexture: Contexture
QuartRond: Présence d'un quard de rond
ChassisCle: Présence d'une clé sur le chassis
FournisseurChassis: Fournisseur chassis
FournisseurToile: Fournisseur toile
Stratigraphie: Stratigraphie
Esthetique: Esthetique
Fragilite: Fragilité
Alteration: Altération
Photo: Photo
Document: Document
Repentir: Repentir
Laboratoire: Laboratoire
Observation: Observation
CoucheObservee: Couche observée
Technique: Technique
NouvellesDonnees: Liste propositions nouvelles données
Zone: zone(s)
Valider: valider
Fermer: fermer
TypeAlteration: Type d'alteration 
TypeIntervention: Type d'intervention 
Initiale: Initiale
PereExamen : Cet examen fait suite à un précédent examen ? 
Revers: Accès revers
AlterationPere: Alteration père
Email: Adresse email
Setting: Paramètres
VerificationKey: clef de vérification
Verifie: Verifié
Active: Actif
Role: Role
Produit: Produit utilisé
TypeDeStockage: Type de stockage
NomExposition: Nom de l'exposition
Favoris: Lieux favoris
AutreLieu: Autre lieu
NouveauEmplacementHP: Ajouter cet emplacement nouveau historique emplacement pour cette oeuvre ?
NouveauEmplacementFavorisHP: Ajouter cet emplacement comme lieu de stockage favoris du propriétaire ?
ModifierImage : Modifier l'image
AjouterImage: Ajouter l'image 
Public: Autorisation de publication
